const filmes = [
  /* The Thing */ { 
    uri: "https://a.ltrbxd.com/resized/sm/upload/t3/qn/vs/p5/s5fH3GqFcHbi2F0NSBSh4KRNTc0-0-500-0-750-crop.jpg?v=01880125bb",
    banner: "https://a.ltrbxd.com/resized/sm/upload/5o/hu/mf/ae/thing-960-960-540-540-crop-000000.jpg?v=1c6f57f7a4",
    titulo: "The Thing",
    ano: 1982,
    avaliacao: "★★★★★",
    data: "20 Jun 2025",
    review: "Um clássico do terror sci-fi, atmosfera tensa e efeitos práticos incríveis.",
    diretor: "John Carpenter",
    duracao: 109,
    sinopse: "A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.",
    tagline: "Man is The Warmest Place to Hide.",
    rating: 4.2,
    fans: "38K",
    friendsWatched: 8,
    friendsWant: 3,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Scott Pilgrim */ { 
    uri: "https://a.ltrbxd.com/resized/sm/upload/vs/75/02/fx/2B5zjs5E3xerqAyowpw3QcOCyLq-0-500-0-750-crop.jpg?v=3aef2095df",
    banner: "https://a.ltrbxd.com/resized/sm/upload/tj/1l/fv/xj/scott-pilgrim-170-960-960-540-540-crop-000000.jpg?v=a57694ded8",
    titulo: "Scott Pilgrim vs. The World",
    ano: 2010,
    avaliacao: "★★★★",
    data: "21 Jun 2025",
    review: "Visualmente criativo, divertido e cheio de referências à cultura pop.",
    diretor: "Edgar Wright",
    duracao: 112,
    sinopse: "As bass guitarist for a garage-rock band, Scott Pilgrim has never had trouble getting a girlfriend; usually, the problem is getting rid of them. But when Ramona Flowers skates into his heart, he finds she has the most troublesome baggage of all: an army of ex-boyfriends who will stop at nothing to eliminate him from her list of suitors.",
    tagline: "An epic of epic epicness.",
    rating: 3.9,
    fans: "29K",
    friendsWatched: 5,
    friendsWant: 2,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Monty Python */ { 
    uri: "https://a.ltrbxd.com/resized/film-poster/5/1/3/9/0/51390-monty-python-and-the-holy-grail-0-500-0-750-crop.jpg?v=a294ae5def",
    banner: "https://a.ltrbxd.com/resized/sm/upload/sx/qk/qr/pj/monty-python-holy-grail-960-960-540-540-crop-000000.jpg?v=c54aef6f32",
    titulo: "Monty Python and the Holy Grail",
    ano: 1975,
    avaliacao: "★★★★½",
    data: "22 Jun 2025",
    review: "Humor britânico absurdo no seu melhor. Icônico!",
    diretor: "Terry Gilliam, Terry Jones",
    duracao: 91,
    sinopse: "King Arthur and his knights embark on a low-budget search for the Grail, encountering many very silly obstacles.",
    tagline: "And now! At last! Another film completely different from some of the other films which aren't quite the same as this one is.",
    rating: 4.1,
    fans: "24K",
    friendsWatched: 4,
    friendsWant: 1,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Perfect Blue */ { 
    uri: "https://a.ltrbxd.com/resized/film-poster/4/6/1/7/5/46175-perfect-blue-0-500-0-750-crop.jpg?v=1ed5878cce",
    banner: "https://a.ltrbxd.com/resized/sm/upload/jf/e4/gt/jx/mHG7dpLb0ZScSY3LpP443IHRmjy-1200-1200-675-675-crop-000000.jpg?v=363b875554",
    titulo: "Perfect Blue",
    ano: 1997,
    avaliacao: "★★★★★",
    data: "23 Jun 2025",
    review: "Psicológico, intenso e perturbador. Uma obra-prima do anime.",
    diretor: "Satoshi Kon",
    duracao: 82,
    sinopse: "Encouraged by her managers, rising pop star Mima takes on a recurring role on a popular TV show, when suddenly her handlers and collaborators begin turning up murdered.",
    tagline: "THE COLOR OF ILLUSION IS PERFECT BLUE.",
    rating: 4.4,
    fans: "45K",
    friendsWatched: 11,
    friendsWant: 7,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Mad God */ { 
    uri: "https://a.ltrbxd.com/resized/film-poster/7/6/1/0/4/6/761046-mad-god-0-500-0-750-crop.jpg?v=ccd8e25d6d",
    banner: "https://a.ltrbxd.com/resized/sm/upload/hg/1x/x4/r5/mad-god-2-960-960-540-540-crop-000000.jpg?v=7b6dd03f17",
    titulo: "Mad God",
    ano: 2021,
    avaliacao: "★★★★½",
    data: "24 Jun 2025",
    review: `"Do it yourself then" taken into a whole other level. This is truly a "nighmerish" work of art, and I love it for all it's worth.
    The whole atmosphere the movie tries to sell you already elevates this movie so much to me.
    Some scenes in this film need to be the dictionary definition of the words "grotesque", "macabre" and others with the same connotation.
    Normally I don't like movies that don't have such a coherent story and just try to sell you with cinematography, but for every rule, there gotta be an exception.`,
    diretor: "Phil Tippett",
    duracao: 83,
    sinopse: "A figure known as “The Assassin” descends from the heavens into a nightmarish pit full of monsters, titans, and cruelty.",
    tagline: "A nightmare 30 years in the making.",
    rating: 4.0,
    fans: "12K",
    friendsWatched: 3,
    friendsWant: 2,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Shaun of the Dead */ { 
    uri: "https://a.ltrbxd.com/resized/sm/upload/36/av/yn/jg/yWEeWO7fLs45XOcb94GPiLrHBRG-0-500-0-750-crop.jpg?v=f9f1d6b3fe",
    banner: "https://a.ltrbxd.com/resized/sm/upload/62/sy/ca/vf/shaun-of-the-dead-960-960-540-540-crop-000000.jpg?v=ad4a57c450",
    titulo: "Shaun of the Dead",
    ano: 2004,
    avaliacao: "★★★½",
    data: "25 Jun 2025",
    review: `It was supposed to be a funny haha movie, why the fuck am I crying towards the ending? Shaun has to be one of my favorite protags I've seen, dude is goofy and relatable in equal medida it's almost incredible.`,
    diretor: "Edgar Wright",
    duracao: 99,
    sinopse: "Shaun lives a supremely uneventful life, which revolves around his girlfriend, his mother, and, above all, his local pub. This gentle routine is threatened when the dead return to life and make strenuous attempts to snack on ordinary Londoners",
    tagline: "A romantic comedy. With zombies.",
    rating: 3.8,
    fans: "18K",
    friendsWatched: 6,
    friendsWant: 2,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Alien */ { 
    uri: "https://a.ltrbxd.com/resized/sm/upload/8v/f1/qw/aa/bg7K6VtUG7Ew70gQj6SSroD5d4R-0-500-0-750-crop.jpg?v=a932f9e98e",
    banner: "https://a.ltrbxd.com/resized/sm/upload/ty/tt/43/of/alien-1979-960-960-540-540-crop-000000.jpg?v=e67d042122",
    titulo: "Alien",
    ano: 1979,
    avaliacao: "★★★★★",
    data: "26 Jun 2025",
    review:  `Fuck it, this movie is peak.

I had a long discussion with a friend about the need for the entire story to have an expanded universe and this must be one of the examples where it wasn't necessary, you may be a fan of all this mythology, but the charm of this film is in the mystery, the Xenomorph being a creature outside of any standard that exists on our planet, without knowing where he veio, not having a complete notion of what he é capaz de, and knowing only that in that small ship...he is there ...among the pipes...waiting for the right moment...this is horror at its finest.`,
    diretor: "Ridley Scott",
    duracao: 117,
    sinopse: "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious lifeform.",
    tagline: "In space no one can hear you scream.",
    rating: 4.3,
    fans: "41K",
    friendsWatched: 9,
    friendsWant: 4,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Esquema Fenicio */ { 
    uri: "https://a.ltrbxd.com/resized/film-poster/1/0/2/5/0/4/7/1025047-the-phoenician-scheme-0-500-0-750-crop.jpg?v=606059b69f",
    banner: "https://a.ltrbxd.com/resized/film-poster/1/0/2/5/0/4/7/1025047-the-phoenician-scheme-0-1200-0-675-crop.jpg?v=606059b69f",
    titulo: "Esquema Fenicio",
    ano: 2023,
    avaliacao: "★★★",
    data: "27 Jun 2025",
    review: `Interestingly ridiculous and honestly that's my kind of thing. Kinda got lost in the story which probably serves a rewatch but nonetheless something cool. Hurts that I had to watch on a small screen this time around.`,
    diretor: "Ana Paula Rocha",
    duracao: 105,
    sinopse: "Um esquema misterioso envolve personagens improváveis em uma trama cheia de reviravoltas.",
    tagline: "Nem tudo é o que parece.",
    rating: 3.2,
    fans: "2K",
    friendsWatched: 1,
    friendsWant: 1,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Samurai de Olhos Azuis */ { 
    uri: "https://a.ltrbxd.com/resized/film-poster/1/0/8/9/0/6/3/1089063-blue-eye-samurai-0-500-0-750-crop.jpg?v=1f468d399d",
    banner: "https://a.ltrbxd.com/resized/film-poster/1/0/8/9/0/6/3/1089063-blue-eye-samurai-0-1200-0-675-crop.jpg?v=1f468d399d",
    titulo: "Samurai de Olhos Azuis",
    ano: 2023,
    avaliacao: "★★★★",
    data: "28 Jun 2025",
    review: `Wow...just...wow

Please don't make this be another case of a great Netflix series that gets cancelled before getting concluded. This is hands down the best samurai story that I have seen since Ghost of Tsushima, I would even dare to say that surpasses it.

The story of Mizu is one of injustice, prejudice, anguish and indiscriminate carnage, but also one of self discovery, where the character transcends the labels they place in order to trap her, and it becomes something bigger, "The Blue-Eyed Samurai".

Another banger from Netflix in the Animation section without a doubt.`,
    diretor: "Michael Green",
    duracao: 50,
    sinopse: "Uma samurai mestiça busca vingança e justiça no Japão feudal.",
    tagline: "Vengeance is blue.",
    rating: 4.0,
    fans: "7K",
    friendsWatched: 2,
    friendsWant: 1,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
 },
  /* Undead Unluck */ { 
    uri: "https://a.ltrbxd.com/resized/film-poster/1/1/4/9/3/6/1/1149361-undead-unluck-0-500-0-750-crop.jpg?v=d9c382d5b6",
    banner: "https://a.ltrbxd.com/resized/film-poster/1/1/4/9/3/6/1/1149361-undead-unluck-0-1200-0-675-crop.jpg?v=d9c382d5b6",
    titulo: "Undead Unluck",
    ano: 2024,
    avaliacao: "★★★½",
    data: "29 Jun 2025",
    review: `Once again reviewing more of the manga than the actual anime, but fuck it, its gonna get adapted one day or another. This as to be the shounen with the most overall absurd and over the top premisse that I have seen.

Even though the anime fails hard on delivering the impact of many scenes. It still doesn't hide the awesome story underneath it, highly recommend it.`,
    diretor: "Yuki Yase",
    duracao: 24,
    sinopse: "Uma garota azarada e um homem imortal enfrentam organizações misteriosas em batalhas absurdas.",
    tagline: "Luck is just the beginning.",
    rating: 3.7,
    fans: "3K",
    friendsWatched: 1,
    friendsWant: 1,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
  /* Superman vs A Elite */ { 
    uri: "https://a.ltrbxd.com/resized/film-poster/8/3/8/2/6/83826-superman-vs-the-elite-0-500-0-750-crop.jpg?v=e4c3b7733a",
    banner: "https://a.ltrbxd.com/resized/film-poster/8/3/8/2/6/83826-superman-vs-the-elite-0-1200-0-675-crop.jpg?v=e4c3b7733a",
    titulo: "Superman vs A Elite",
    ano: 2012,
    avaliacao: "★★★",
    data: "30 Jun 2025",
    review: `It's actually pretty impressive that they can tell a story so close to the core of who superman is without the bigger villains in play. this story one of the best examples of what Superman stands for. Showing just how horrific things can be if we give in to our worst nature's, and how the better path isn't always the easiest or one we think is going to make us feel better.

Still one of the best animated comic-book movies story-wise. And it's not even close.`,
    diretor: "Michael Chang",
    duracao: 76,
    sinopse: "Superman enfrenta um novo grupo de vigilantes superpoderosos que desafiam seus ideais.",
    tagline: "Worlds Collide. Ideals Survive.",
    rating: 3.5,
    fans: "5K",
    friendsWatched: 2,
    friendsWant: 1,
    ratingBars: [2, 3, 5, 8, 12, 18, 22, 28, 35, 40],
  },
];

export default filmes;